language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-north' ]; then cd .. && eval "mv $currentfolder generator-north" && cd generator-north; fi

